# https://discuss.circleci.com/t/tag-workflow-doesnt-work-despite-similar-setup-on-other-project-working/30514/8
# https://discuss.circleci.com/t/workflow-is-not-triggered-by-tag-push/30498
# https://circleci.com/docs/api/#trigger-a-new-build-with-a-branch
version: 2.1

jobs:
  versions:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: versions
          command: |
            echo "CIRCLE_BRANCH=${CIRCLE_BRANCH}"

  install:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: install
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

  test:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: test
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

  build:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: build
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

  deploy-pre:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: deploy-pre
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

  deploy-normal:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: deploy-normal
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

  deploy-test:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: deploy-test
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - versions
      - install:
          filters:
            tags:
              only: /v.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /v.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /v.*/
      - deploy-pre:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - deploy-normal:
          requires:
            - deploy-pre
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v(\d)+(\.(\d)+)+/
      - deploy-test:
          requires:
            - deploy-pre
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(v(\d)+(\.(\d)+)+)-(alpha|beta)/
