# https://discuss.circleci.com/t/tag-workflow-doesnt-work-despite-similar-setup-on-other-project-working/30514/8
# https://discuss.circleci.com/t/workflow-is-not-triggered-by-tag-push/30498
# https://circleci.com/docs/api/#trigger-a-new-build-with-a-branch
version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: build
          command: |
            echo "CIRCLE_BRANCH=${CIRCLE_BRANCH} CIRCLE_TAG=${CIRCLE_TAG}"

  deploy:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: deploy
          command: |
            echo "CIRCLE_BRANCH=${CIRCLE_BRANCH} CIRCLE_TAG=${CIRCLE_TAG}"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
          requires:
            - build

