version: 2.1

jobs:
  always:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: always
          command: |
            echo "CIRCLE_BRANCH=${CIRCLE_BRANCH}"

  tags:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - run:
          name: tags
          command: |
            echo "CIRCLE_TAG=${CIRCLE_TAG}"

workflows:
  version: 2
  all:
    jobs:
      - always
      - tags:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - always